Traceback (most recent call last):
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/mmadeira/anaconda3/envs/IPC-2020-21/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Garantimos que a fun√ß√£o n√£o √© usada de forma incorreta.
paridade_2(5.0)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-4-b199af80c7d1>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Garantimos que a fun√ß√£o n√£o √© usada de forma incorreta.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mparidade_2[0m[0;34m([0m[0;36m5.0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-1-747bfba24ad1>[0m in [0;36mparidade_2[0;34m(n)[0m
[1;32m     14[0m         [0;34m'Par'[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m     """
[0;32m---> 16[0;31m     [0;32massert[0m [0mtype[0m[0;34m([0m[0mn[0m[0;34m)[0m [0;32mis[0m [0mint[0m[0;34m,[0m [0;34m"n n√£o √© um inteiro: %r"[0m [0;34m%[0m [0mn[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     17[0m     [0;32massert[0m [0mn[0m [0;34m>[0m[0;36m0[0m[0;34m,[0m [0;34m"n n√£o √© maior que zero: %r"[0m [0;34m%[0m [0mn[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m     [0;32mwhile[0m [0;34m([0m[0mn[0m[0;34m>[0m[0;36m2[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAssertionError[0m: n n√£o √© um inteiro: 5.0
AssertionError: n n√£o √© um inteiro: 5.0

